CC=gcc
CFLAGS=-Wall -Wextra -Werror
DEFINE=-D BUFFER_SIZE=8
NAME=main
OBJS=$(SRCS:.c=.o)
SRCS=get_next_line.c\
get_next_line_utils.c

all: 
	$(CC) -I/Users/sm/42seoul_inner/gnl $(DEFINE) -o $(NAME) -g main.c $(SRCS) 
clean: 
	rm $(name)
fclean:
	rm $(name)